-- Actividad 3.2

-- CASO 1 INCOMPLETO PORQUE FALTA LA TABLA MOVILIZACION ADICIONAL
-- DOCUMENTO WORD MAL ESCRITO

/*

SET SERVEROUTPUT ON;

-- Bean para ingresar el año del proceso

VAR B_ANNO_PROCESO NUMBER
EXEC :B_ANNO_PROCESO:=2020;

-- Bean para ingresar comuna a la que se le paga movilizacion adicional

VAR B_COMUNA VARCHAR2
EXEC :B_COMUNA:='María Pinto';

-- Bean para ingresar el valor de la movilizacion adicional para la comuna

VAR B_VALOR_MOVIL_EXTRA NUMBER
EXEC :B_VALOR_MOVIL_EXTRA:=20000;

-- Bean para ingresar el run del empleado

VAR B_RUT NUMBER
EXEC :B_RUT:=11846972;

DECLARE

V_IDCOMUNA EMPLEADO.ID_COMUNA%TYPE;

V_NUMRUN EMPLEADO.NUMRUN_EMP%TYPE;
V_DVRUN EMPLEADO.DVRUN_EMP%TYPE;
V_NOMBRE VARCHAR2(113);
V_SUELDO EMPLEADO.SUELDO_BASE%TYPE;
V_PORC_MOVIL_NORMAL NUMBER(2);
V_VALOR_MOVIL_NORMAL NUMBER(6);

BEGIN

SELECT ID_COMUNA -- ID_COMUNA para ocuparla en otra sentencia SELECT
INTO V_IDCOMUNA
FROM COMUNA
WHERE NOMBRE_COMUNA =:B_COMUNA;

SELECT NUMRUN_EMP,
DVRUN_EMP,
PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
SUELDO_BASE,
TRUNC(SUELDO_BASE/100000), --PORC_MOVIL_NORMAL
SUELDO_BASE*(TRUNC(SUELDO_BASE/100000)/100) --VALOR_MOVIL_NORMAL
IF ID_COMUNA = V_IDCOMUNA THEN


END IF;
INTO V_NUMRUN, V_DVRUN, V_NOMBRE, V_SUELDO, V_PORC_MOVIL_NORMAL, V_VALOR_MOVIL_NORMAL
FROM EMPLEADO
WHERE NUMRUN_EMP =:B_RUT;



END;

*/