-- Actividad 3.4

-- CASO 1

-- Bean para definir el año del proceso

/*

VAR B_ANNO_PROCESO NUMBER
EXEC :B_ANNO_PROCESO:=EXTRACT(YEAR FROM SYSDATE);

-- 5 Beans de comunas a las que se les paga movilización adicional
-- 5 Beans de los valores de movilización adicional para las comunas indicadas
VAR B_C1 VARCHAR2
EXEC :B_C1:='María Pinto';
VAR B_CV1 NUMBER
EXEC :B_CV1:=20000;

VAR B_C2 VARCHAR2
EXEC :B_C2:='Curacaví';
VAR B_CV2 NUMBER
EXEC :B_CV2:=25000;

VAR B_C3 VARCHAR2
EXEC :B_C3:='Talagante';
VAR B_CV3 NUMBER
EXEC :B_CV3:=30000;

VAR B_C4 VARCHAR2
EXEC :B_C4:='El Monte';
VAR B_CV4 NUMBER
EXEC :B_CV4:=35000;

VAR B_C5 VARCHAR2
EXEC :B_C5:='Buin';
VAR B_CV5 NUMBER
EXEC :B_CV5:=40000;

DECLARE

V_MIN EMPLEADO.ID_EMP%TYPE;
V_MAX EMPLEADO.ID_EMP%TYPE;

V_NUMRUN_EMP EMPLEADO.NUMRUN_EMP%TYPE;
V_DVRUN_EMP EMPLEADO.DVRUN_EMP%TYPE;
V_NOMBRE VARCHAR2(113);
V_ID_COMUNA EMPLEADO.ID_COMUNA%TYPE;
V_SUELDO_BASE EMPLEADO.SUELDO_BASE%TYPE;

V_COMUNA COMUNA.NOMBRE_COMUNA%TYPE;

V_PORC_MOVIL PROY_MOVILIZACION.PORC_MOVIL_NORMAL%TYPE;
V_VALOR_MOVIL PROY_MOVILIZACION.VALOR_MOVIL_NORMAL%TYPE;
V_VALOR_ADICIONAL PROY_MOVILIZACION.VALOR_MOVIL_EXTRA%TYPE;
V_VALOR_TOTAL PROY_MOVILIZACION.VALOR_TOTAL_MOVIL%TYPE;

BEGIN

EXECUTE IMMEDIATE('TRUNCATE TABLE PROY_MOVILIZACION');

SELECT MIN(ID_EMP),
MAX(ID_EMP)
INTO V_MIN, V_MAX
FROM EMPLEADO;

WHILE(V_MIN<=V_MAX) LOOP

SELECT
NUMRUN_EMP,
DVRUN_EMP,
PNOMBRE_EMP||' '||SNOMBRE_EMP||' '||APPATERNO_EMP||' '||APMATERNO_EMP,
ID_COMUNA,
SUELDO_BASE
INTO V_NUMRUN_EMP, V_DVRUN_EMP, V_NOMBRE, V_ID_COMUNA, V_SUELDO_BASE
FROM EMPLEADO
WHERE ID_EMP=V_MIN;

SELECT NOMBRE_COMUNA
INTO V_COMUNA
FROM COMUNA
WHERE ID_COMUNA=V_ID_COMUNA;

V_PORC_MOVIL:=TRUNC(V_SUELDO_BASE/100000);

V_VALOR_MOVIL:=V_SUELDO_BASE*(V_PORC_MOVIL/100);

IF(V_COMUNA=:B_C1)THEN
V_VALOR_ADICIONAL:=:B_CV1;
ELSIF(V_COMUNA=:B_C2)THEN
V_VALOR_ADICIONAL:=:B_CV2;
ELSIF(V_COMUNA=:B_C3)THEN
V_VALOR_ADICIONAL:=:B_CV3;
ELSIF(V_COMUNA=:B_C4)THEN
V_VALOR_ADICIONAL:=:B_CV4;
ELSIF(V_COMUNA=:B_C5)THEN
V_VALOR_ADICIONAL:=:B_CV5;
ELSE
V_VALOR_ADICIONAL:=0;
END IF;

V_VALOR_TOTAL:=V_VALOR_MOVIL+V_VALOR_ADICIONAL;

INSERT INTO PROY_MOVILIZACION(ANNO_PROCESO,ID_EMP, NUMRUN_EMP,DVRUN_EMP, NOMBRE_EMPLEADO,
NOMBRE_COMUNA,SUELDO_BASE,PORC_MOVIL_NORMAL,VALOR_MOVIL_NORMAL,VALOR_MOVIL_EXTRA,VALOR_TOTAL_MOVIL)
VALUES(:B_ANNO_PROCESO, V_MIN, V_NUMRUN_EMP, V_DVRUN_EMP, V_NOMBRE, V_COMUNA, V_SUELDO_BASE, V_PORC_MOVIL, V_VALOR_MOVIL, V_VALOR_ADICIONAL, V_VALOR_TOTAL);

COMMIT;

V_MIN:=V_MIN+10;

END LOOP;

END;

/*