-- Actividad 3.3

-- CASO 1

/*

-- Bean para ingresar RUN del cliente

VAR B_RUN NUMBER
EXEC :B_RUN:=21242003;

DECLARE

V_NRO_CLIENTE CLIENTE.NRO_CLIENTE%TYPE;
V_RUN VARCHAR2(12);
V_NOMBRE VARCHAR(203);
V_COD_TIPO_CLIENTE CLIENTE.COD_TIPO_CLIENTE%TYPE;

V_TIPO_CLIENTE TIPO_CLIENTE.NOMBRE_TIPO_CLIENTE%TYPE;

V_MONTO_SOLICITADO_ANIO CREDITO_CLIENTE.MONTO_SOLICITADO%TYPE;

V_MONTO_TODOSUMA CLIENTE_TODOSUMA.MONTO_PESOS_TODOSUMA%TYPE;

BEGIN

-- SENTENCIA SELECT PARA ASIGNAR DATOS DEL CLIENTE A LAS VARIBLES
SELECT NRO_CLIENTE,
NUMRUN||'-'||DVRUN,
PNOMBRE||' '||SNOMBRE||' '||APPATERNO||' '||APMATERNO,
COD_TIPO_CLIENTE
INTO V_NRO_CLIENTE, V_RUN, V_NOMBRE, V_COD_TIPO_CLIENTE
FROM CLIENTE
WHERE NUMRUN =:B_RUN;

-- SENTENCIA SELECT PARA ASIGNAR EL TIPO DE CLIENTE A UNA VARIABLE
SELECT NOMBRE_TIPO_CLIENTE
INTO V_TIPO_CLIENTE
FROM TIPO_CLIENTE
WHERE COD_TIPO_CLIENTE = V_COD_TIPO_CLIENTE;

-- SENTENCIA SELECT PARA ASIGNAR EL TOTAL DE MONTOS SOLICITADOS DEL ANIO ANTERIOR
SELECT SUM(MONTO_SOLICITADO)
INTO V_MONTO_SOLICITADO_ANIO
FROM CREDITO_CLIENTE
WHERE NRO_CLIENTE = V_NRO_CLIENTE AND EXTRACT(YEAR FROM FECHA_SOLIC_CRED) = EXTRACT(YEAR FROM SYSDATE)-1;

-- ASIGNANDO UN VALOR A UNA VARIABLE SEGUN QUE CONDICION SE CUMPLA EN EL CASE
V_MONTO_TODOSUMA :=
CASE
    WHEN V_MONTO_SOLICITADO_ANIO < 1000000 -- MENOR A $1.000.000
    THEN TRUNC(V_MONTO_SOLICITADO_ANIO/100000)*(1200+100) -- 100$ EXTRA POR CADA $100.000 DEL MONTO SOLICITADO
    WHEN V_MONTO_SOLICITADO_ANIO >= 1000000 AND V_MONTO_SOLICITADO_ANIO < 3000000 -- $1.000.001 - $3.000.000
    THEN TRUNC(V_MONTO_SOLICITADO_ANIO/100000)*(1200+300) -- 300$ EXTRA POR CADA $100.000 DEL MONTO SOLICITADO
    WHEN V_MONTO_SOLICITADO_ANIO > 3000000 -- MAYOR A $3.000.000
    THEN TRUNC(V_MONTO_SOLICITADO_ANIO/100000)*(1200+550) -- 550$ EXTRA POR CADA $100.000 DEL MONTO SOLICITADO
END;

INSERT INTO CLIENTE_TODOSUMA(NRO_CLIENTE, RUN_CLIENTE, NOMBRE_CLIENTE, TIPO_CLIENTE, MONTO_SOLIC_CREDITOS, MONTO_PESOS_TODOSUMA)
VALUES(V_NRO_CLIENTE, V_RUN, V_NOMBRE, V_TIPO_CLIENTE, V_MONTO_SOLICITADO_ANIO, V_MONTO_TODOSUMA);

END;

*/