/* Creación de usuario si está trabajando con BD Oracle Cloud */
CREATE USER BDY1102_P14 IDENTIFIED BY "Blockbuzter"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P14 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_P14;
GRANT "RESOURCE" TO BDY1102_P14;
ALTER USER BDY1102_P14 DEFAULT ROLE "RESOURCE";
