-- Caso 1
SET SERVEROUTPUT ON;

DECLARE

CURSOR CUR_ATENCION IS 
SELECT P.PAC_RUN,
P.DV_RUN,
INITCAP(P.PNOMBRE||' '||P.SNOMBRE||' '||P.APATERNO||' '||P.AMATERNO) AS NOMBREP,
A.ATE_ID,
PA.FECHA_VENC_PAGO,
PA.FECHA_PAGO,
PA.FECHA_PAGO-PA.FECHA_VENC_PAGO AS DIASM,
E.NOMBRE AS NOMBRE_ESP,
TRUNC(MONTHS_BETWEEN(SYSDATE,P.FECHA_NACIMIENTO)/12) AS EDADP
FROM ATENCION A
INNER JOIN PACIENTE P ON (A.PAC_RUN=P.PAC_RUN)
INNER JOIN PAGO_ATENCION PA ON (A.ATE_ID=PA.ATE_ID)
INNER JOIN ESPECIALIDAD E ON(A.ESP_ID=E.ESP_ID)
WHERE PA.FECHA_PAGO-PA.FECHA_VENC_PAGO>0 AND TO_CHAR(PA.FECHA_VENC_PAGO,'YYYY')=TO_CHAR(SYSDATE,'YYYY')-1
ORDER BY PA.FECHA_VENC_PAGO ASC, P.APATERNO ASC;

V_MULTA PAGO_MOROSO.MONTO_MULTA%TYPE;
V_PORCENTAJE PORC_DESCTO_3RA_EDAD.PORCENTAJE_DESCTO%TYPE;
V_MULTA_FINAL PAGO_MOROSO.MONTO_MULTA%TYPE;

BEGIN

EXECUTE IMMEDIATE('TRUNCATE TABLE PAGO_MOROSO');

FOR REG_ATENCION IN CUR_ATENCION LOOP
    IF(REG_ATENCION.NOMBRE_ESP='Cirugía General' OR REG_ATENCION.NOMBRE_ESP='Dermatología')THEN
        V_MULTA := REG_ATENCION.DIASM*1200;
    ELSIF(REG_ATENCION.NOMBRE_ESP='Ortopedia y Traumatología')THEN
        V_MULTA := REG_ATENCION.DIASM*1300; 
    ELSIF(REG_ATENCION.NOMBRE_ESP='Inmunología' OR REG_ATENCION.NOMBRE_ESP='Otorrinolaringología')THEN
        V_MULTA := REG_ATENCION.DIASM*1700;
    ELSIF(REG_ATENCION.NOMBRE_ESP='Fisiatría' OR REG_ATENCION.NOMBRE_ESP='Medicina Interna')THEN
        V_MULTA := REG_ATENCION.DIASM*1900;
    ELSIF(REG_ATENCION.NOMBRE_ESP='Medicina General')THEN
        V_MULTA := REG_ATENCION.DIASM*1100;
    ELSIF(REG_ATENCION.NOMBRE_ESP='Psiquiatría Adultos')THEN
        V_MULTA := REG_ATENCION.DIASM*1100;
    ELSIF(REG_ATENCION.NOMBRE_ESP='Cirugía Digestiva' OR REG_ATENCION.NOMBRE_ESP='Reumatología')THEN
        V_MULTA := REG_ATENCION.DIASM*2300;
    ELSE
        V_MULTA := REG_ATENCION.DIASM*900;
    END IF;
    
    IF(REG_ATENCION.EDADP>=65 AND REG_ATENCION.EDADP<=120)THEN
        SELECT PORCENTAJE_DESCTO
        INTO V_PORCENTAJE
        FROM PORC_DESCTO_3RA_EDAD
        WHERE REG_ATENCION.EDADP BETWEEN ANNO_INI AND ANNO_TER;
    ELSE
        V_PORCENTAJE := 0;
    END IF;
    
    V_MULTA_FINAL := V_MULTA-(V_MULTA*V_PORCENTAJE/100);
    
    INSERT INTO PAGO_MOROSO
    (PAC_RUN, PAC_DV_RUN, PAC_NOMBRE, ATE_ID, FECHA_VENC_PAGO, FECHA_PAGO, DIAS_MOROSIDAD, ESPECIALIDAD_ATENCION, MONTO_MULTA)
    VALUES(REG_ATENCION.PAC_RUN, REG_ATENCION.DV_RUN, REG_ATENCION.NOMBREP, REG_ATENCION.ATE_ID, REG_ATENCION.FECHA_VENC_PAGO,
    REG_ATENCION.FECHA_PAGO, REG_ATENCION.DIASM, REG_ATENCION.NOMBRE_ESP, V_MULTA_FINAL);
    COMMIT;
END LOOP;

END;

-- Caso 2
SET SERVEROUTPUT ON;

DECLARE

CURSOR CUR_MEDICO IS
SELECT U.NOMBRE AS UNIDAD,
TO_CHAR(M.MED_RUN,'99G999G999')||'-'||UPPER(M.DV_RUN) AS RUN_MEDICO,
INITCAP(M.PNOMBRE||' '||M.SNOMBRE||' '||M.APATERNO||' '||M.AMATERNO) AS NOMBRE_MEDICO,
SUBSTR(U.NOMBRE,1,2)||SUBSTR(M.APATERNO,-3,2)||'@medicocktk.cl' AS CORREO_INSTITUCIONAL,
COUNT(A.ATE_ID) AS TOTAL_ATEN_MEDICAS
FROM ATENCION A
INNER JOIN MEDICO M ON(A.MED_RUN=M.MED_RUN)
INNER JOIN UNIDAD U ON(M.UNI_ID=U.UNI_ID)
WHERE TO_CHAR(A.FECHA_ATENCION,'YYYY')=TO_CHAR(SYSDATE,'YYYY')-1
GROUP BY U.NOMBRE, M.MED_RUN, M.DV_RUN, M.PNOMBRE, M.SNOMBRE, M.APATERNO, M.AMATERNO
ORDER BY U.NOMBRE ASC, M.APATERNO ASC
;

V_DESTINACION MEDICO_SERVICIO_COMUNIDAD.DESTINACION%TYPE;

BEGIN

EXECUTE IMMEDIATE('TRUNCATE TABLE MEDICO_SERVICIO_COMUNIDAD');

FOR REG_MEDICO IN CUR_MEDICO LOOP

    IF(REG_MEDICO.UNIDAD='ATENCIÓN ADULTO' OR REG_MEDICO.UNIDAD='ATENCIÓN AMBULATORIA')THEN
        V_DESTINACION := 'Servicio de Atención Primaria de Urgencia (SAPU)';
    ELSIF(REG_MEDICO.UNIDAD='ATENCIÓN URGENCIA' AND REG_MEDICO.TOTAL_ATEN_MEDICAS<=3 AND REG_MEDICO.TOTAL_ATEN_MEDICAS>=1)THEN
        V_DESTINACION := 'Servicio de Atención Primaria de Urgencia (SAPU)';
    ELSIF(REG_MEDICO.UNIDAD='ATENCIÓN URGENCIA' AND REG_MEDICO.TOTAL_ATEN_MEDICAS>3)THEN
        V_DESTINACION := 'Hospitales del área de la Salud Pública';
    ELSIF(REG_MEDICO.UNIDAD='CARDIOLOGÍA' OR REG_MEDICO.UNIDAD='ONCOLÓGICA')THEN
        V_DESTINACION := 'Hospitales del área de la Salud Pública';
    ELSIF(REG_MEDICO.UNIDAD='CIRUGÍA' OR REG_MEDICO.UNIDAD='CIRUGÍA PLÁSTICA' AND REG_MEDICO.TOTAL_ATEN_MEDICAS<=3 AND REG_MEDICO.TOTAL_ATEN_MEDICAS>=1)THEN
        V_DESTINACION := 'Servicio de Atención Primaria de Urgencia (SAPU)';
    ELSIF(REG_MEDICO.UNIDAD='CIRUGÍA' OR REG_MEDICO.UNIDAD='CIRUGÍA PLÁSTICA' AND REG_MEDICO.TOTAL_ATEN_MEDICAS>3)THEN
        V_DESTINACION := 'Hospitales del área de la Salud Pública';
    ELSIF(REG_MEDICO.UNIDAD='PACIENTE CRÍTICO')THEN
        V_DESTINACION := 'Hospitales del área de la Salud Pública';
    ELSIF(REG_MEDICO.UNIDAD='PSIQUIATRÍA Y SALUD MENTAL')THEN
        V_DESTINACION := 'Centros de Salud Familiar (CESFAM)';
    ELSIF(REG_MEDICO.UNIDAD='TRAUMATOLOGÍA ADULTO' AND REG_MEDICO.TOTAL_ATEN_MEDICAS<=3 AND REG_MEDICO.TOTAL_ATEN_MEDICAS>=1)THEN
        V_DESTINACION := 'Servicio de Atención Primaria de Urgencia (SAPU)';
    ELSIF(REG_MEDICO.UNIDAD='TRAUMATOLOGÍA ADULTO' AND REG_MEDICO.TOTAL_ATEN_MEDICAS>3)THEN
        V_DESTINACION := 'Hospitales del área de la Salud Pública';
    ELSE
        V_DESTINACION := '';
    END IF;
    
    INSERT INTO MEDICO_SERVICIO_COMUNIDAD(UNIDAD, RUN_MEDICO, NOMBRE_MEDICO, CORREO_INSTITUCIONAL, TOTAL_ATEN_MEDICAS, DESTINACION)
    VALUES(REG_MEDICO.UNIDAD, REG_MEDICO.RUN_MEDICO, REG_MEDICO.NOMBRE_MEDICO, REG_MEDICO.CORREO_INSTITUCIONAL, REG_MEDICO.TOTAL_ATEN_MEDICAS, V_DESTINACION);
END LOOP;

END;